"""
deploy.py
─────────
A Dockerfile for **one bundle**, built from what that bundle actually declares.

The repository Dockerfile has fixed targets — `serve` for the deep-learning stack,
`serve-gbdt` without torch. They cover the common cases and they are guesses about
which case you are in. A bundle already knows: `manifest.requires` lists exactly
the libraries its backend needs, recorded at training time by the plugin that
needed them.

So this reads the manifest and emits an image that installs *those* extras and no
others. The payoff is the same one `serve-gbdt` demonstrated in P3 — a booster
image without torch is roughly 500 MB lighter, with a cold start to match — except
it now follows from the bundle rather than from the user picking the right target.

Generated, not templated into the repo: a Dockerfile committed next to the code
would go stale the moment a plugin's requirements changed, and the staleness would
be invisible until an image failed to serve.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from .core.types import DIST_NAME, FrameworkError

log = logging.getLogger(__name__)

# The base image the repository Dockerfile uses. Kept in step deliberately —
# generating an image on a different Python than CI tests against is a way to
# discover a version-specific bug in production.
BASE_IMAGE = "python:3.11-slim"

# Always needed to serve anything, whatever the model is.
SERVING_EXTRAS: tuple[str, ...] = ("serve",)


class DeployError(FrameworkError):
    """A deployable image could not be described for this bundle."""


def required_extras(manifest: Any) -> list[str]:
    """The extras this bundle's model needs, from its own recorded requirements.

    Reads `manifest.requires` — written at training time from the plugin's
    `ModelSpec.requires` — rather than mapping the backend name to a guess. A
    third-party plugin declaring its own extra therefore gets a correct image
    without this module knowing the plugin exists.
    """
    extras = {ref.extra for ref in manifest.requires if getattr(ref, "extra", None)}
    return sorted(extras | set(SERVING_EXTRAS))


def render_dockerfile(bundle_dir: str | Path, *, base_image: str = BASE_IMAGE) -> str:
    """A Dockerfile that serves ``bundle_dir`` and installs nothing more.

    The bundle is **copied in** rather than mounted: an image that needs a volume
    to be useful is not a deployable artifact, and the whole point of the bundle
    format is that it is self-contained.
    """
    from .core.bundle import read_manifest

    source = Path(bundle_dir)
    if not source.is_dir():
        raise DeployError(f"no bundle directory at {source}")

    manifest = read_manifest(source)
    extras = required_extras(manifest)
    spec = f"{DIST_NAME}[{','.join(extras)}]"

    torch_free = not any(extra in ("lightning", "image", "nlp") for extra in extras)
    weight_note = (
        "# No torch in this image: this model does not need it. That is roughly\n"
        "# 500 MB and a cold start the deep-learning image pays and this one does not."
        if torch_free
        else "# This model needs the deep-learning runtime, so torch is installed\n"
        "# CPU-only -- the CUDA build adds several GB of nvidia wheels."
    )
    torch_install = (
        ""
        if torch_free
        else "\n# CPU-only torch, in its own layer so it caches across rebuilds above it.\n"
        "RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu\n"
    )

    lines = f"""# Generated by `mlf dockerfile` for the bundle at {source.name}
#
# Tailored to what this bundle *declares* it needs -- `manifest.requires`, written
# at training time by the plugin that needed them -- rather than to a fixed target
# somebody had to pick correctly.
#
#   model    {manifest.model.name} ({manifest.model.backend} backend)
#   task     {manifest.task} on {manifest.data_kind} data
#   extras   {", ".join(extras)}
#
{weight_note}

FROM {base_image}

WORKDIR /app
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
{torch_install}
COPY pyproject.toml README.md ./
COPY src/ ./src/
RUN pip install --no-cache-dir '.[{",".join(extras)}]'

# The bundle is copied in, not mounted: an image that needs a volume to be useful
# is not a deployable artifact.
COPY {source.name}/ ./bundle/

# Serving reads MLF_* from the environment -- MLF_API_KEY (secret),
# MLF_RATE_LIMIT, MLF_MAX_INSTANCES. See serving/asgi.py.
ENV MLF_ARTIFACTS=/app/bundle
EXPOSE 8000

# Health: GET /health   Metrics: GET /metrics
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s \\
  CMD python -c "import urllib.request;urllib.request.urlopen('http://localhost:8000/health')"

CMD ["mlf", "serve", "--artifacts", "/app/bundle", "--host", "0.0.0.0", "--port", "8000"]
"""
    log.info("dockerfile for %s: extras=%s (%s)", manifest.model.name, extras, spec)
    return lines


__all__ = ["BASE_IMAGE", "DeployError", "render_dockerfile", "required_extras"]
