"""Per-bundle Dockerfile generation.

The repository Dockerfile has fixed targets — `serve` with the deep-learning
stack, `serve-gbdt` without. They are guesses about which case you are in. A
bundle already knows: `manifest.requires` lists exactly what its backend needs,
recorded at training time by the plugin that needed it.

So the property under test is that the generated image installs what the *bundle*
declares, not what a target name assumed — and in particular that a booster image
does not install torch, which is the ~500 MB the fixed targets existed to save.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from ml_framework.core.bundle import (
    InputSignature,
    Manifest,
    ModelRef,
    OutputSignature,
    RequirementRef,
    Signature,
    write_bundle,
)
from ml_framework.core.types import Requirement
from ml_framework.deploy import DeployError, excluded_by, render_dockerfile, required_extras


def make_bundle(dest: Path, *, name: str, backend: str, requires: list[Requirement]) -> Path:
    manifest = Manifest(
        task="multiclass",
        data_kind="tabular",
        model=ModelRef(name=name, backend=backend, artifact="model/m.json", format="native"),
        signature=Signature(
            input=InputSignature(payload="arrays", features=["a", "b"], n_features=2),
            output=OutputSignature(kind="probabilities", n_classes=3),
        ),
        requires=[RequirementRef.from_requirement(r) for r in requires],
    )
    write_bundle(dest, manifest)
    return dest


# ── What it installs ──────────────────────────────────────
@pytest.mark.unit
def test_a_booster_image_does_not_install_torch(tmp_path):
    """The payoff the fixed `serve-gbdt` target demonstrated, now following from
    the bundle rather than from the user picking the right target."""
    bundle = make_bundle(
        tmp_path / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt", min_version="2.0")],
    )

    text = render_dockerfile(bundle)
    assert "gbdt" in text and "serve" in text
    assert "download.pytorch.org" not in text
    assert "No torch in this image" in text


@pytest.mark.unit
def test_a_neural_image_installs_cpu_only_torch(tmp_path):
    """The CUDA build adds several GB of nvidia wheels for a serving container
    that will not use them."""
    bundle = make_bundle(
        tmp_path / "b",
        name="mlp",
        backend="lightning",
        requires=[Requirement("torch", extra="lightning", min_version="2.0")],
    )

    text = render_dockerfile(bundle)
    assert "download.pytorch.org/whl/cpu" in text
    assert "lightning" in text


@pytest.mark.unit
def test_extras_come_from_the_bundles_own_requirements(tmp_path):
    """Not from a backend-name lookup. A third-party plugin declaring its own
    extra gets a correct image without this module knowing the plugin exists."""
    bundle = make_bundle(
        tmp_path / "b",
        name="third.party",
        backend="gbdt",
        requires=[Requirement("weirdlib", extra="somethingelse")],
    )

    assert required_extras(
        __import__("ml_framework.core.bundle", fromlist=["x"]).read_manifest(bundle)
    ) == [
        "serve",
        "somethingelse",
    ]


@pytest.mark.unit
def test_serving_extras_are_always_present(tmp_path):
    """Whatever the model is, the image has to be able to serve it."""
    bundle = make_bundle(tmp_path / "b", name="ts.naive", backend="forecast", requires=[])

    assert "serve" in required_extras(
        __import__("ml_framework.core.bundle", fromlist=["x"]).read_manifest(bundle)
    )


# ── What the file says ────────────────────────────────────
@pytest.mark.unit
def test_the_header_records_what_the_image_is_for(tmp_path):
    """A generated Dockerfile with no provenance is one nobody can safely edit."""
    bundle = make_bundle(
        tmp_path / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )

    text = render_dockerfile(bundle)
    assert "xgboost (gbdt backend)" in text
    assert "multiclass on tabular data" in text
    assert "Generated by `mlf dockerfile`" in text


@pytest.mark.unit
def test_the_bundle_is_copied_not_mounted(tmp_path):
    """An image that needs a volume to be useful is not a deployable artifact,
    and the whole point of the bundle format is that it is self-contained."""
    bundle = make_bundle(
        tmp_path / "mybundle",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )

    text = render_dockerfile(bundle)
    assert "COPY mybundle/ ./bundle/" in text
    assert "VOLUME" not in text


@pytest.mark.unit
def test_a_missing_bundle_says_so(tmp_path):
    with pytest.raises(DeployError, match="no bundle directory"):
        render_dockerfile(tmp_path / "absent")


# ── The build context ─────────────────────────────────────
# A generated Dockerfile is only correct relative to the context it will be built
# from, and that context was previously implicit: the bundle was copied by its
# basename (assuming the context is the bundle's parent) while `src/` and
# `pyproject.toml` were copied by name (assuming the context is the repository
# root). The two coincide only for a bundle sitting directly in the root — which
# is the default, `outputs/`, and which this repository's own .dockerignore
# strips. The default configuration was the broken one.
@pytest.mark.unit
def test_a_dockerignored_bundle_is_refused_rather_than_copied_as_nothing(tmp_path):
    """The failure this replaces was invisible in the worst way: the build
    succeeds, the image is produced, and `COPY` quietly contributes an empty
    directory. Nothing goes wrong until the container starts and cannot find a
    manifest — by which point the evidence is a serving log, not a build log."""
    bundle = make_bundle(
        tmp_path / "outputs",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    (tmp_path / ".dockerignore").write_text("__pycache__\noutputs\n*.pkl\n", encoding="utf-8")

    with pytest.raises(DeployError, match=r"strips 'outputs'"):
        render_dockerfile(bundle)


@pytest.mark.unit
def test_the_documented_fix_actually_works(tmp_path):
    """The refusal above tells the reader to add `!outputs`. Docker's rule is
    last-match-wins, so that has to re-include the bundle — an error message
    that sends people somewhere unhelpful is worse than no message."""
    bundle = make_bundle(
        tmp_path / "outputs",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    (tmp_path / ".dockerignore").write_text("outputs\n!outputs\n", encoding="utf-8")

    assert "COPY outputs/ ./bundle/" in render_dockerfile(bundle)


@pytest.mark.unit
def test_excluding_a_parent_directory_excludes_the_bundle_under_it(tmp_path):
    """Docker excludes a matched directory's whole subtree, so a pattern has to
    be tested against every parent prefix and not only the full path. Checking
    the path alone would miss `artifacts` stripping `artifacts/run7`."""
    assert excluded_by("artifacts/run7", tmp_path) is None  # no .dockerignore at all

    (tmp_path / ".dockerignore").write_text("artifacts\n", encoding="utf-8")
    assert excluded_by("artifacts/run7", tmp_path) == "artifacts"


@pytest.mark.unit
def test_the_copy_path_is_relative_to_the_context_not_the_basename(tmp_path):
    """A bundle nested deeper than one level under the context must be copied by
    the path the context can resolve. The basename form named a directory that
    does not exist at the context root, so COPY had nothing to match."""
    nested = tmp_path / "artifacts" / "run7"
    make_bundle(
        nested, name="xgboost", backend="gbdt", requires=[Requirement("xgboost", extra="gbdt")]
    )

    text = render_dockerfile(nested, context=tmp_path)

    assert "COPY artifacts/run7/ ./bundle/" in text
    assert "COPY run7/" not in text


@pytest.mark.unit
def test_a_bundle_outside_the_context_is_refused(tmp_path):
    """COPY cannot reach outside a build context. Emitting a path that climbs out
    of it produces a Dockerfile that cannot build anywhere."""
    bundle = make_bundle(
        tmp_path / "elsewhere" / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    context = tmp_path / "context"
    context.mkdir()

    with pytest.raises(DeployError, match="not inside the build context"):
        render_dockerfile(bundle, context=context)


# ── The CLI ───────────────────────────────────────────────
@pytest.mark.unit
def test_mlf_dockerfile_writes_the_file(tmp_path, capsys):
    from ml_framework import cli

    bundle = make_bundle(
        tmp_path / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    destination = tmp_path / "Dockerfile.serve"

    assert cli.main(["dockerfile", "-a", str(bundle), "-o", str(destination)]) == 0
    assert destination.read_text(encoding="utf-8").startswith("# Generated by")


@pytest.mark.unit
def test_mlf_dockerfile_refuses_to_overwrite_without_force(tmp_path):
    from ml_framework import cli

    bundle = make_bundle(
        tmp_path / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    destination = tmp_path / "Dockerfile.serve"
    destination.write_text("existing\n", encoding="utf-8")

    assert cli.main(["dockerfile", "-a", str(bundle), "-o", str(destination)]) == 1
    assert destination.read_text(encoding="utf-8") == "existing\n"
    assert cli.main(["dockerfile", "-a", str(bundle), "-o", str(destination), "--force"]) == 0


@pytest.mark.unit
def test_the_manifest_is_readable_after_generation(tmp_path):
    """Generation must not touch the bundle it describes."""
    bundle = make_bundle(
        tmp_path / "b",
        name="xgboost",
        backend="gbdt",
        requires=[Requirement("xgboost", extra="gbdt")],
    )
    before = json.loads((bundle / "manifest.json").read_text(encoding="utf-8"))

    render_dockerfile(bundle)

    assert json.loads((bundle / "manifest.json").read_text(encoding="utf-8")) == before
